'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    'à l'aide d'un outil, tel que ResGen ou Visual Studio.
    'Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    'avec l'option /str ou régénérez votre projet VS.
    '''<summary>
    '''  Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Core
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ANS.SecureFrameworkLib.Core", GetType(Core).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Remplace la propriété CurrentUICulture du thread actuel pour toutes
        '''  les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The configuration dictionary is not initialized..
        '''</summary>
        Friend Shared ReadOnly Property CONFIG_NOTHING() As String
            Get
                Return ResourceManager.GetString("CONFIG_NOTHING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: folder &quot;{1}&quot; could not be created..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_FOLDER_CREATE() As String
            Get
                Return ResourceManager.GetString("ERROR_FOLDER_CREATE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: folder &quot;{1}&quot; is read only.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_FOLDER_READONLY() As String
            Get
                Return ResourceManager.GetString("ERROR_FOLDER_READONLY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value {1} must not be greater than {2}..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_INT_MAX_VALUE() As String
            Get
                Return ResourceManager.GetString("ERROR_INT_MAX_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value {1} must not be lesser than {2}..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_INT_MIN_VALUE() As String
            Get
                Return ResourceManager.GetString("ERROR_INT_MIN_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Value {0} is not strictly lesser than {1}..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_INT_RANGE() As String
            Get
                Return ResourceManager.GetString("ERROR_INT_RANGE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a boolean..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_BOOL() As String
            Get
                Return ResourceManager.GetString("INVALID_BOOL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a valid email address..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_EMAIL() As String
            Get
                Return ResourceManager.GetString("INVALID_EMAIL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a valid file name..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_FILE_NAME() As String
            Get
                Return ResourceManager.GetString("INVALID_FILE_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a valid folder name..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("INVALID_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The identifier name is invalid..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_ID_NAME() As String
            Get
                Return ResourceManager.GetString("INVALID_ID_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like an integer..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_INT() As String
            Get
                Return ResourceManager.GetString("INVALID_INT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a number..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_NUMBER() As String
            Get
                Return ResourceManager.GetString("INVALID_NUMBER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à The parameter name is invalid..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_PARAM_NAME() As String
            Get
                Return ResourceManager.GetString("INVALID_PARAM_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: value &quot;{1}&quot; does not look like a valid URL..
        '''</summary>
        Friend Shared ReadOnly Property INVALID_URL() As String
            Get
                Return ResourceManager.GetString("INVALID_URL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: file &quot;{1}&quot; does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MISSING_FILE() As String
            Get
                Return ResourceManager.GetString("MISSING_FILE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot;: folder &quot;{1}&quot; does not exist..
        '''</summary>
        Friend Shared ReadOnly Property MISSING_FOLDER() As String
            Get
                Return ResourceManager.GetString("MISSING_FOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Identifier &quot;{0}&quot; is missing..
        '''</summary>
        Friend Shared ReadOnly Property MISSING_ID() As String
            Get
                Return ResourceManager.GetString("MISSING_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Recherche une chaîne localisée semblable à Parameter &quot;{0}&quot; is missing..
        '''</summary>
        Friend Shared ReadOnly Property MISSING_PARAM() As String
            Get
                Return ResourceManager.GetString("MISSING_PARAM", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
